// === src/main/java/com/sachin/foododering/model/User.java ===
package com.sachin.foododering.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "users")
public class User {

    @Id
    private String id;  // MongoDB-generated ID

    private String username;
    private String password;
    private String role; // "ADMIN" or "CUSTOMER"
    private String email;  // New field for email
    private String mobileNumber;  // New field for mobile number

    // Additional getters and setters will be generated by Lombok
}
